### ISSUE TITLE
在非绘制线程里面使用setText()时会报错

### ISSUE THREAD

**Issue by karamay00** [tianqiujie/nativefont#4]
java.lang.RuntimeException: No OpenGL context found in the current thread.
	at org.lwjgl.opengl.GLContext.getCapabilities(GLContext.java:124)
	at org.lwjgl.opengl.GL11.glBindTexture(GL11.java:651)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glBindTexture(LwjglGL20.java:93)
	at com.badlogic.gdx.graphics.GLTexture.bind(GLTexture.java:66)
	at com.badlogic.gdx.graphics.Texture.load(Texture.java:136)
	at com.badlogic.gdx.graphics.g2d.PixmapPacker$Page.updateTexture(PixmapPacker.java:378)
	at net.mwplay.nativefont.NativeFont.upData(NativeFont.java:259)
	at net.mwplay.nativefont.NativeFont.create(NativeFont.java:212)
	at net.mwplay.nativefont.NativeFont.appendText(NativeFont.java:176)
	at net.mwplay.nativefont.NativeLabel.append(NativeLabel.java:50)
	at net.mwplay.nativefont.NativeLabel.<init>(NativeLabel.java:43)
	at net.mwplay.nativefont.NativeLabel.<init>(NativeLabel.java:38)
	at net.mwplay.nativefont.NativeLabel.<init>(NativeLabel.java:33)
	at com.yuyointeractive.utils.MyScreen.getNativeLabel(MyScreen.java:141)
	at com.yuyointeractive.jiangximahjong.StartScreen.popTip(StartScreen.java:673)

**Comment by badboy-tian** [comment]
fixed. https://jitpack.io/#tianqiujie/nativefont
